// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migcontentstatusadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migcontentstatusadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202405070622217_mig-content-status-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
