// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migaboutcolumnaddedonwritertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migaboutcolumnaddedonwritertable));
        
        string IMigrationMetadata.Id
        {
            get { return "202405020747357_mig-about-column-added-on-writer-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
