// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class writeridcolumnadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(writeridcolumnadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202404240830284_writer-id-column-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
