// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class for_primary_key_error : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(for_primary_key_error));
        
        string IMigrationMetadata.Id
        {
            get { return "202405150819118_for_primary_key_error"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
